name: Continuous Integeration

on:
  push:
    branches:
      - workflow-test

jobs:
  install-and-test:
    name: Install npm dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Clean previous build
        run: cd android && chmod +x ./gradlew && ./gradlew clean

      - name: Build dev apk
        run: cd android && chmod +x ./gradlew && ./gradlew assembleDebug

      - name: Build release apk
        run: cd android && chmod +x ./gradlew && ./gradlew assembleRelease

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-release.apk
      #     path: android/app/build/outputs/apk/release/

      - name: Archive build
        uses: thedoctor0/zip-release@master
        with:
          filename: 'app-release.zip'

      - name: Upload Artifact zip
        uses: actions/upload-artifact@v1
        with:
          name: app-release.zip
          path: android/app/build/outputs/apk/release/

      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Literal body:
          # body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          body: file://README.md
          to: fashionfiest05@gmail.com
          from: Shubham Roy # <user@example.com>
          # Optional carbon copy recipients
          # cc: kyloren@starkiller.com,leia@alderaan.com
          # Optional blind carbon copy recipients
          # bcc: r2d2@jakku.com,hansolo@milleniumfalcon.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: app-release.zip



  # build-android:
  #   - needs: install-and-test
  #   - runs-on: ubuntu-latest
  #   - steps: 
  #     - name: Build android release
  #       run: cd android && ./gradlew assembleRelease
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v1
  #       with: 
  #         name: app-release.apk
  #         path: android/app/build/outputs/apk/release/
