name: Continuous Integeration

on:
  push:
    branches:
      - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

  build-android:
    # - needs: install-dependencies
    - runs-on: ubuntu-latest
    - steps: 
      - name: Build android release
        run: cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with: 
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
